export const timezones = [
   { value: "-12", label: "(GMT-12:00) Linha Internacional de Data Oeste" },
   { value: "-11", label: "(GMT-11:00) Horário Universal Coordenado-11" },
   { value: "-10", label: "(GMT-10:00) Havaí" },
   { value: "-9.5", label: "(GMT-09:30) Ilhas Marquesas" },
   { value: "-9", label: "(GMT-09:00) Alasca" },
   { value: "-8", label: "(GMT-08:00) Horário do Pacífico (EUA e Canadá)" },
   { value: "-7", label: "(GMT-07:00) Horário das Montanhas (EUA e Canadá)" },
   {
      value: "-6",
      label: "(GMT-06:00) Horário Central (EUA e Canadá), Cidade do México",
   },
   {
      value: "-5",
      label: "(GMT-05:00) Horário do Leste (EUA e Canadá), Bogotá, Lima",
   },
   { value: "-4", label: "(GMT-04:00) Horário do Atlântico (Canadá), Manaus" },
   { value: "-3.5", label: "(GMT-03:30) Newfoundland" },
   { value: "-3", label: "(GMT-03:00) Brasília, Buenos Aires, Groenlândia" },
   { value: "-2", label: "(GMT-02:00) Meio-Atlântico" },
   { value: "-1", label: "(GMT-01:00) Açores, Ilhas de Cabo Verde" },
   {
      value: "0",
      label: "(GMT+00:00) Horário da Europa Ocidental, Londres, Lisboa",
   },
   { value: "1", label: "(GMT+01:00) Bruxelas, Copenhague, Madri, Paris" },
   { value: "2", label: "(GMT+02:00) Kaliningrado, África do Sul" },
   { value: "3", label: "(GMT+03:00) Bagdá, Riad, Moscou, São Petersburgo" },
   { value: "3.5", label: "(GMT+03:30) Teerã" },
   { value: "4", label: "(GMT+04:00) Abu Dhabi, Mascate, Baku, Tbilisi" },
   { value: "4.5", label: "(GMT+04:30) Cabul" },
   {
      value: "5",
      label: "(GMT+05:00) Ecaterimburgo, Islamabad, Karachi, Tashkent",
   },
   { value: "5.5", label: "(GMT+05:30) Mumbai, Calcutá, Chennai, Nova Deli" },
   { value: "5.75", label: "(GMT+05:45) Katmandu" },
   { value: "6", label: "(GMT+06:00) Almaty, Daca, Colombo" },
   { value: "6.5", label: "(GMT+06:30) Yangon (Rangoon)" },
   { value: "7", label: "(GMT+07:00) Bangkok, Hanói, Jacarta" },
   { value: "8", label: "(GMT+08:00) Pequim, Perth, Singapura, Hong Kong" },
   { value: "8.75", label: "(GMT+08:45) Eucla" },
   { value: "9", label: "(GMT+09:00) Tóquio, Seul, Osaka, Sapporo, Yakutsk" },
   { value: "9.5", label: "(GMT+09:30) Adelaide, Darwin" },
   { value: "10", label: "(GMT+10:00) Leste da Austrália, Guam, Vladivostok" },
   { value: "10.5", label: "(GMT+10:30) Ilha de Lord Howe" },
   { value: "11", label: "(GMT+11:00) Magadan, Ilhas Salomão, Nova Caledônia" },
   { value: "12", label: "(GMT+12:00) Auckland, Wellington, Fiji, Kamchatka" },
   { value: "12.75", label: "(GMT+12:45) Ilhas Chatham" },
   { value: "13", label: "(GMT+13:00) Nuku'alofa" },
   { value: "14", label: "(GMT+14:00) Kiribati" },
];